// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvoOCG27J80yrxg2vtnBiVgeAe0tilHBE',
    appId: '1:948355163106:web:c5b8e0d72dedbc80134fbb',
    messagingSenderId: '948355163106',
    projectId: 'portfolioapp-aa6fc',
    authDomain: 'portfolioapp-aa6fc.firebaseapp.com',
    storageBucket: 'portfolioapp-aa6fc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFwfBQ1z_PsWUls94dYXHhDEgCCGE5a6A',
    appId: '1:948355163106:android:0d1c50aa328a8793134fbb',
    messagingSenderId: '948355163106',
    projectId: 'portfolioapp-aa6fc',
    storageBucket: 'portfolioapp-aa6fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC62Yl3UgAJKO3fDNKXg9420AM4C8a0ioI',
    appId: '1:948355163106:ios:ff62b83664070860134fbb',
    messagingSenderId: '948355163106',
    projectId: 'portfolioapp-aa6fc',
    storageBucket: 'portfolioapp-aa6fc.firebasestorage.app',
    iosClientId: '948355163106-3nn64ekhqdpume408ma1dkk2e4fmj5jv.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC62Yl3UgAJKO3fDNKXg9420AM4C8a0ioI',
    appId: '1:948355163106:ios:ff62b83664070860134fbb',
    messagingSenderId: '948355163106',
    projectId: 'portfolioapp-aa6fc',
    storageBucket: 'portfolioapp-aa6fc.firebasestorage.app',
    iosClientId: '948355163106-3nn64ekhqdpume408ma1dkk2e4fmj5jv.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolioApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvoOCG27J80yrxg2vtnBiVgeAe0tilHBE',
    appId: '1:948355163106:web:e28e99ed2510fb96134fbb',
    messagingSenderId: '948355163106',
    projectId: 'portfolioapp-aa6fc',
    authDomain: 'portfolioapp-aa6fc.firebaseapp.com',
    storageBucket: 'portfolioapp-aa6fc.firebasestorage.app',
  );

}